/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;
import clases.Hora;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class Princpal extends javax.swing.JFrame {

    /**
     * Creates new form Princpal
     */
    public Princpal() {
        initComponents();
        cmdIgualar.setEnabled(false);
        cmdMayor.setEnabled(false);
        cmdMenor.setEnabled(false);
        cmdMostrar.setEnabled(false);
        cmdValidar.setEnabled(false);
        cmdValidar1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMm1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSs1 = new javax.swing.JTextField();
        txtHh2 = new javax.swing.JTextField();
        txtMm2 = new javax.swing.JTextField();
        txtHH1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSs2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        cmdIgualar = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdValidar1 = new javax.swing.JButton();
        cmdValidar = new javax.swing.JButton();
        cmdMayor = new javax.swing.JButton();
        cmdMenor = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmdCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 640, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 710, 130));

        jLabel1.setText("Hora n°2");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        jLabel2.setText("Hora n°1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        txtMm1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMm1KeyTyped(evt);
            }
        });
        jPanel1.add(txtMm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 40, -1));

        jLabel3.setText("MM");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jLabel4.setText("SS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        txtSs1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSs1KeyTyped(evt);
            }
        });
        jPanel1.add(txtSs1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 40, -1));

        txtHh2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHh2KeyTyped(evt);
            }
        });
        jPanel1.add(txtHh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 40, -1));

        txtMm2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMm2KeyTyped(evt);
            }
        });
        jPanel1.add(txtMm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 40, -1));

        txtHH1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHH1KeyTyped(evt);
            }
        });
        jPanel1.add(txtHH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 40, -1));

        jLabel7.setText("HH");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 40, -1));

        jLabel8.setText("HH");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        txtSs2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSs2KeyTyped(evt);
            }
        });
        jPanel1.add(txtSs2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 40, -1));

        jLabel9.setText("MM");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel5.setText("SS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdIgualar.setText("Igualar");
        cmdIgualar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIgualarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdIgualar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, -1, -1));

        cmdMostrar.setText("Mostar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        cmdValidar1.setText("Validar hora 2");
        cmdValidar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValidar1ActionPerformed(evt);
            }
        });
        jPanel3.add(cmdValidar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cmdValidar.setText("Validar hora 1");
        cmdValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdValidarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        cmdMayor.setText("Mayor");
        cmdMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMayorActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        cmdMenor.setText("Menor");
        cmdMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMenorActionPerformed(evt);
            }
        });
        jPanel3.add(cmdMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        cmdBorrar.setForeground(new java.awt.Color(102, 0, 0));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        cmdCrear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmdCrear.setForeground(new java.awt.Color(0, 153, 0));
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 340, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(806, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        Hora h;
        int hora1 ,hora2 , minuto1 , minuto2 , segundo1 , segundo2;
        if(txtHH1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la hora de La Hora 1");
            txtHH1.requestFocusInWindow();
        }else if(txtMm1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite los minutos de La Hora 1");
            txtMm1.requestFocusInWindow();
        }else if(txtSs1.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite los segundos de La Hora 1");
            txtSs1.requestFocusInWindow();
        }else if(txtHh2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite las Horas de La Hora 2");
            txtHh2.requestFocusInWindow();
        }else if(txtMm2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite los minutos de La Hora 2");
            txtMm2.requestFocusInWindow();
        }else if(txtSs2.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite los segundos de La Hora 2");
            txtSs2.requestFocusInWindow();
        }
        hora1= Integer.parseInt(txtHH1.getText());
       minuto1 = Integer.parseInt(txtMm1.getText());
       segundo1 = Integer.parseInt(txtSs1.getText()); 
       hora2 =Integer.parseInt(txtHh2.getText());
        
        minuto2 = Integer.parseInt(txtMm2.getText());
        
        segundo2 = Integer.parseInt(txtSs2.getText());
        h = new Hora (segundo1 ,minuto1 ,hora1);
        JOptionPane.showMessageDialog(this, "Creado");
        cmdCrear.setEnabled(false);
        cmdIgualar.setEnabled(true);
        cmdMayor.setEnabled(true);
        cmdMenor.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdValidar.setEnabled(true);
        cmdValidar1.setEnabled(true);

    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValidarActionPerformed
       Hora h;
        String aux;
        int h1 , m ,s; 
        h1 = Integer.parseInt (txtHH1.getText());
        m = Integer.parseInt (txtMm1.getText());
        s = Integer.parseInt (txtSs1.getText());
        h = new Hora (h1 ,m ,s);
        aux = h.validarh1();
        txtArea.setText(aux);
        
        cmdCrear.setEnabled(false);
        cmdIgualar.setEnabled(true);
        cmdMayor.setEnabled(true);
        cmdMenor.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdValidar1.setEnabled(false);
        cmdValidar.setEnabled(true);
    }//GEN-LAST:event_cmdValidarActionPerformed

    private void cmdMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMayorActionPerformed
       Hora h;
        String aux;
        int h1,m1,s1 , h2  , m2  , s2;
        h1= Integer.parseInt(txtHH1.getText());
         m1 = Integer.parseInt(txtMm1.getText());
        s1 = Integer.parseInt(txtSs1.getText());
         h2 =Integer.parseInt(txtHh2.getText());
        m2 = Integer.parseInt(txtMm2.getText());  
        s2 = Integer.parseInt(txtSs2.getText());
        
         h = new Hora (h1 ,m1 ,s1);
         aux = h.mayor(h2,m2,s2);
        
       txtArea.setText(aux);
        cmdCrear.setEnabled(false);
        cmdIgualar.setEnabled(false);
        cmdMayor.setEnabled(false);
        cmdMenor.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdValidar1.setEnabled(false);
        cmdValidar.setEnabled(false);
    }//GEN-LAST:event_cmdMayorActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed
       Hora h;
        String aux;
        int h1,m1,s1 , h2  , m2  , s2;
        h1= Integer.parseInt(txtHH1.getText());
         m1 = Integer.parseInt(txtMm1.getText());
        s1 = Integer.parseInt(txtSs1.getText());
         h2 =Integer.parseInt(txtHh2.getText());
        m2 = Integer.parseInt(txtMm2.getText());  
        s2 = Integer.parseInt(txtSs2.getText());
        
       h = new Hora (h1 ,m1 ,s1);
         aux = h.mostrar(h2,m2,s2);
         txtArea.setText(aux);
        cmdCrear.setEnabled(false);
        cmdIgualar.setEnabled(false);
        cmdMayor.setEnabled(false);
        cmdMenor.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdValidar1.setEnabled(false);
        cmdValidar.setEnabled(false);
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdValidar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdValidar1ActionPerformed
       Hora h;
        String aux;
        int h1 , m ,s; 
        h1 = Integer.parseInt (txtHh2.getText());
        m = Integer.parseInt (txtMm2.getText());
        s = Integer.parseInt (txtSs2.getText());
        h = new Hora (h1 ,m ,s);
        aux = h.validarh1();
        txtArea.setText(aux);
        
        cmdCrear.setEnabled(false);
        cmdIgualar.setEnabled(true);
        cmdMayor.setEnabled(true);
        cmdMenor.setEnabled(true);
        cmdMostrar.setEnabled(true);
        cmdValidar1.setEnabled(false);
        cmdValidar.setEnabled(true);
    }//GEN-LAST:event_cmdValidar1ActionPerformed

    private void cmdMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMenorActionPerformed
       Hora h;
        String aux;
        int h1,m1,s1 , h2  , m2  , s2;
        h1= Integer.parseInt(txtHH1.getText());
         m1 = Integer.parseInt(txtMm1.getText());
        s1 = Integer.parseInt(txtSs1.getText());
         h2 =Integer.parseInt(txtHh2.getText());
        m2 = Integer.parseInt(txtMm2.getText());  
        s2 = Integer.parseInt(txtSs2.getText());
        
         h = new Hora (h1 ,m1 ,s1);
         aux = h.Menor(h2,m2,s2);
        
       txtArea.setText(aux);
        cmdCrear.setEnabled(false);
        cmdIgualar.setEnabled(false);
        cmdMayor.setEnabled(false);
        cmdMenor.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdValidar1.setEnabled(false);
        cmdValidar.setEnabled(false);
    }//GEN-LAST:event_cmdMenorActionPerformed

    private void cmdIgualarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIgualarActionPerformed
         Hora h;
        String aux;
        int h1,m1,s1 , h2  , m2  , s2;
         h1= Integer.parseInt(txtHH1.getText());
         m1 = Integer.parseInt(txtMm1.getText());
        s1 = Integer.parseInt(txtSs1.getText());
         h2 =Integer.parseInt(txtHh2.getText());
        m2 = Integer.parseInt(txtMm2.getText());  
        s2 = Integer.parseInt(txtSs2.getText());
        
         h = new Hora (h1 ,m1 ,s1);
         aux = h.Igual(h2,m2,s2);
       txtArea.setText(aux);
        cmdCrear.setEnabled(false);
        cmdIgualar.setEnabled(false);
        cmdMayor.setEnabled(false);
        cmdMenor.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdValidar1.setEnabled(false);
        cmdValidar.setEnabled(false);
    }//GEN-LAST:event_cmdIgualarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       txtArea.setText("");
        cmdCrear.setEnabled(true);
        cmdIgualar.setEnabled(false);
        cmdMayor.setEnabled(false);
        cmdMenor.setEnabled(false);
        cmdMostrar.setEnabled(true);
        cmdValidar1.setEnabled(false);
        cmdValidar.setEnabled(false);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtHH1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHH1KeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
        
    }//GEN-LAST:event_txtHH1KeyTyped

    private void txtMm1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMm1KeyTyped
char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtMm1KeyTyped

    private void txtSs1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSs1KeyTyped
char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSs1KeyTyped

    private void txtHh2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHh2KeyTyped
char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtHh2KeyTyped

    private void txtMm2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMm2KeyTyped
char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtMm2KeyTyped

    private void txtSs2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSs2KeyTyped
char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSs2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Princpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Princpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdIgualar;
    private javax.swing.JButton cmdMayor;
    private javax.swing.JButton cmdMenor;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdValidar;
    private javax.swing.JButton cmdValidar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtHH1;
    private javax.swing.JTextField txtHh2;
    private javax.swing.JTextField txtMm1;
    private javax.swing.JTextField txtMm2;
    private javax.swing.JTextField txtSs1;
    private javax.swing.JTextField txtSs2;
    // End of variables declaration//GEN-END:variables
}
